CREATE TABLE users(
    uuid VARCHAR(36) PRIMARY KEY,
    username VARCHAR(70) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT NOW() NOT NULL
);