// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db_sqlc

import (
	"context"
)

const getUserPasswordForLogin = `-- name: GetUserPasswordForLogin :one
SELECT password FROM users WHERE username = ? OR email = ?
`

type GetUserPasswordForLoginParams struct {
	Username string
	Email    string
}

func (q *Queries) GetUserPasswordForLogin(ctx context.Context, arg GetUserPasswordForLoginParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordForLogin, arg.Username, arg.Email)
	var password string
	err := row.Scan(&password)
	return password, err
}

const isEmailTaken = `-- name: IsEmailTaken :one
SELECT 1 FROM users WHERE email = ?
`

func (q *Queries) IsEmailTaken(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRowContext(ctx, isEmailTaken, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const isPhoneTaken = `-- name: IsPhoneTaken :one
SELECT 1 FROM users WHERE phone = ?
`

func (q *Queries) IsPhoneTaken(ctx context.Context, phone string) (int32, error) {
	row := q.db.QueryRowContext(ctx, isPhoneTaken, phone)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const isUsernameTaken = `-- name: IsUsernameTaken :one
SELECT 1 FROM users WHERE username = ?
`

func (q *Queries) IsUsernameTaken(ctx context.Context, username string) (int32, error) {
	row := q.db.QueryRowContext(ctx, isUsernameTaken, username)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const registerUser = `-- name: RegisterUser :exec
INSERT INTO users (uuid, username, email, phone, password) VALUES
    (?, ?, ?, ?, ?)
`

type RegisterUserParams struct {
	Uuid     string
	Username string
	Email    string
	Phone    string
	Password string
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) error {
	_, err := q.db.ExecContext(ctx, registerUser,
		arg.Uuid,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.Password,
	)
	return err
}
